# Generated by Django 4.0.2 on 2022-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='supplier',
            field=models.ManyToManyField(blank=True, related_name='supplier', to='inventory.Supplier'),
        ),
    ]
